USE master
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'WHJHNativeWebDB')
DROP DATABASE [WHJHNativeWebDB]
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'WHJHPlatformManagerDB')
DROP DATABASE [WHJHPlatformManagerDB]
GO


/****** Object:  Database [WHJHNativeWebDB]    Script Date: 2017/7/13 17:49:26 ******/
CREATE DATABASE [WHJHNativeWebDB] ON  PRIMARY 
( NAME = N'WHJHNativeWebDB', FILENAME = N'D:\数据库\精华平台\WHJHNativeWebDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WHJHNativeWebDB_log', FILENAME = N'D:\数据库\精华平台\WHJHNativeWebDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WHJHNativeWebDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WHJHNativeWebDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [WHJHNativeWebDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WHJHNativeWebDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WHJHNativeWebDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WHJHNativeWebDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WHJHNativeWebDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WHJHNativeWebDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WHJHNativeWebDB] SET  MULTI_USER 
GO

ALTER DATABASE [WHJHNativeWebDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WHJHNativeWebDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WHJHNativeWebDB] SET  READ_WRITE 
GO

/****** Object:  Database [WHJHPlatformManagerDB]    Script Date: 2017/7/13 17:50:29 ******/
CREATE DATABASE [WHJHPlatformManagerDB] ON  PRIMARY 
( NAME = N'RY_WHJHPlatformManagerDB', FILENAME = N'D:\数据库\精华平台\WHJHPlatformManagerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RY_WHJHPlatformManagerDB_log', FILENAME = N'D:\数据库\精华平台\WHJHPlatformManagerDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WHJHPlatformManagerDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET  MULTI_USER 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WHJHPlatformManagerDB] SET  READ_WRITE 
GO